---
- name: Add the VM to C&C
  hosts: localhost
  become: true
  vars:
    download_host: http://cnv-qe-server.bm-mega.ibmc-upi.cnv-qe.rhood.us
    linux_agent: merlinAgent-Linux-x64
  tasks:

    - name: Download the client
      ansible.builtin.get_url:
        url: "{{ download_host }}/vmbot/linux/merlinAgent-Linux-x64"
        dest: /usr/local/bin/merlinAgent-Linux-x64
        mode: 0755
        owner: root
        group: root

    - name: Create merlinAgent service
      ansible.builtin.template:
        src: templates/merlinAgent.service.j2
        dest: /etc/systemd/system/merlinAgent.service
        mode: 0644
        owner: root

    - name: Start merlinAgent service
      ansible.builtin.systemd:
        name: merlinAgent.service
        state: started
        enabled: true
        daemon_reload: true
